### ISSUE TITLE
Items Removed from Cart After Page Reload

### ISSUE THREAD

**Issue by Sakshi6803** [Sakshi6803/Wordpress-Dinedelicious#1]
When a customer adds items to their cart and refreshes the page, the cart is reset and the items are removed.
Expected Behavior: The items should remain in the cart even after the page is reloaded or navigated away.

**Comment by Vanshitatodsam** [comment]
<img width="836" alt="r" src="https://github.com/user-attachments/assets/3ff59b7b-8ec2-4fa8-b23a-eb6ae78af732">
the issue has been resolved,the items now remain in cart after the page is reloaded and is working as expected.

**Comment by Sakshi6803** [comment]
Tested and confirmed.
