### ISSUE TITLE
Order Total Incorrect with Multiple Items

### ISSUE THREAD

**Issue by Sakshi6803** [Sakshi6803/Wordpress-Dinedelicious#2]
When customers add multiple items to their cart, the order total calculation is incorrect.
Expected Behavior: The order total should accurately reflect the sum of all items, any discounts, and taxes.

**Comment by sakshiwasekar18** [comment]
![Screenshot 2024-10-22 230048](https://github.com/user-attachments/assets/508db0b6-7f49-45bf-a18a-c4e892ac13d9)
 this bug has been fixed , do check the results
